use journey;

insert into musica values 
-- Insert .MP3
(null,"Meu Poeta","Samba","Arlindo Cruz","Arlindo Cruz - Meu Poeta.mp3"),
(null,"Retalhos de Cetim","Samba","Benito di Paula","Benito di Paula - Retalhos de Cetim.mp3"),
(null,"Treasure","Disco/Pop","Bruno Mars","Bruno Mars -  Treasure.mp3"),
(null,"Locked Out Of Heaven","Pop Rock","Bruno Mars","Bruno Mars - Locked Out Of Heaven.mp3"),
(null,"Cigarette Dreams","Alternativo","Cage The Elephant","Cage The Elephant - Cigarette Dreams.mp3"),
(null,"Come a little Closer","Alternativo","Cage the Elephant","Cage the Elephant - Come a little Closer.mp3"),
(null,"Safe and Sound","Alternativo","Capital Cities","Capital Cities - Safe and Sound.mp3"),
(null,"Gold","Dance","Chet Faker","Chet Faker - Gold.mp3"),
(null,"I'm Into You","R&B/Soul","Chet Faker","Chet Faker - I'm Into You.mp3"),
(null,"No Diggity","R&B/Soul","Chet Faker","Chet Faker - No Diggity.mp3"),
(null,"Ser Humano","Samba","Claudemir","Claudemir - Ser Humano.mp3"),
(null,"Charlie Brown","Dance","Coldplay","Coldplay - Charlie Brown.mp3"),
(null,"Every Teardrop Is a Waterfall","Dance","Coldplay","Coldplay - Every Teardrop Is a Waterfall.mp3"),
(null,"Magic","Pop","Coldplay","Coldplay - Magic.mp3"),
(null,"Paradise","Pop","Coldplay","Coldplay - Paradise.mp3"),
(null,"Speed of Sound","Rock","Coldplay","Coldplay - Speed of Sound.mp3"),
(null,"The Scientist","Rock Alternativo","Coldplay","Coldplay - The Scientist.mp3"),
(null,"Trouble","Soft Rock","Coldplay","Coldplay - Trouble.mp3"),
(null,"Viva La Vida","Pop Barroco","Coldplay","Coldplay - Viva La Vida.mp3"),
(null,"Yellow","Rock","Coldplay","Coldplay - Yellow.mp3"),
(null,"Lama nas Ruas","Samba","Diogo Nogueira","Diogo Nogueira - Lama nas Ruas.mp3"),
(null,"Letreiro","Samba","Dunga","Dunga - Letreiro.mp3"),
(null,"Hoje é dia de Festa","Samba","Efson","Efson - Hoje é dia de Festa.mp3"),
(null,"Can You Feel The Love Tonight","Soft Rock","Elton John","Elton John - Can You Feel The Love Tonight.mp3"),
(null,"Bad Love","Rock","Eric Clapton","Eric Clapton - Bad Love.mp3"),
(null,"Best of You","Rock","Foo Fighters","Foo Fighters - Best of You.mp3"),
(null,"Everlong","Rock","Foo Fighters","Foo Fighters - Everlong.mp3"),
(null,"Learn to Fly","Rock","Foo Fighters","Foo Fighters - Learn to Fly.mp3"),
(null,"The Pretender","Rock","Foo Fighters","Foo Fighters - The Pretender.mp3"),
(null,"Times Like These","Rock","Foo Fighters","Foo Fighters - Times Like These.mp3"),
(null,"Walk","Rock","Foo Fighters","Foo Fighters - Walk.mp3"),
(null,"Vida da Minha Vida","Samba","Fundo de Quintal","Fundo de Quintal - Vida da Minha Vida.mp3"),
(null,"Listen to the Man","Folk","George Erza","George Erza - Listen to the Man.mp3"),
(null,"Blame it on Me","Blues","Gerorge Erza","Gerorge Erza - Blame it on Me.mp3"),
(null,"Somebody I Used to Know","Alternativo","Gotye","Gotye - Somebody I Used to Know.mp3"),
(null,"Aventureiro  - Velocidade da Luz","Samba","Grupo Revelação","Grupo Revelação - Aventureiro  - Velocidade da Luz.mp3"),
(null,"Essencia da Paixao","Samba","Grupo Revelação","Grupo Revelação - Essencia da Paixao.mp3"),
(null,"Homenagem Sambistas Perfeitos","Samba","Grupo Revelação","Grupo Revelação - Homenagem Sambistas Perfeitos.mp3"),
(null,"Novos Tempos","Samba","Grupo Revelação","Grupo Revelação - Novos Tempos.mp3"),
(null,"So depois - Deixa Acontecer Naturalmente","Samba","Grupo Revelação","Grupo Revelação - So depois -Deixa Acontecer Naturalmente.mp3"),
(null,"Banana Pancakes","Rock","Jack Johnson","Jack Johnson - Banana Pancakes.mp3"),
(null,"Better Together","Rock Acustico","Jack Johnson","Jack Johnson - Better Together.mp3"),
(null,"Breakdown","Pop Rock","Jack Johnson","Jack Johnson - Breakdown.mp3"),
(null,"Sitting, Waiting, Wishing","Rock","Jack Johnson","Jack Johnson - Sitting, Waiting, Wishing.mp3"),
(null,"Hold Back The River","Alternativo","James Bay","James Bay - Hold Back The River.mp3"),
(null,"Empire State of Mind","Hip-Hop/Rap","Jay Z","Jay Z - Empire State of Mind.mp3"),
(null,"Hold My Hand","Dance/Pop","Jess Glyne","Jess Glyne - Hold My Hand.mp3"),
(null,"All of Me","R&B/Soul","John Legend","John Legend - All of Me.mp3"),
(null,"Daylight","Alternativo","Joji","Joji - Daylight.mp3"),
(null,"Ew","Alternativo","Joji","Joji - Ew.mp3"),
(null,"High Hopes","Alternativo","Joji","Joji - High Hopes.mp3"),
(null,"Like You Do","Alternativo","Joji","Joji - Like You Do.mp3"),
(null,"MODUS","Alternativo","Joji","Joji - MODUS.mp3"),
(null,"NITROUS","Alternativo","Joji","Joji - NITROUS.mp3"),
(null,"Normal People","Alternativo","Joji","Joji - Normal People.mp3"),
(null,"Reanimator","Alternativo","Joji","Joji - Reanimator.mp3"),
(null,"Tick Tock","Alternativo","Joji","Joji - Tick Tock.mp3"),
(null,"Your Man","Alternativo","Joji","Joji - Your Man.mp3"),
(null,"Afterthought","Alternativo","Joji","Joji - Afterthought.mp3"),
(null,"Suit and Tie","Pop","Justin Timberlake","Justin Timberlake - Suit and Tie.mp3"),
(null,"Use Somebody","Rock","Kings of Leon","Kings of Leon -  Use Somebody.mp3"),
(null,"Sex On Fire","Rock","Kings of Leon","Kings of Leon - Sex On Fire.mp3"),
(null,"Ogum","Samba","Marquinhos PQD","Marquinhos PQD - Ogum.mp3"),
(null,"Down by the River","Pop","Milky Chance","Milky Chance - Down by the River.mp3"),
(null,"Flashed Junk Mind","Pop","Milky Chance","Milky Chance - Flashed Junk Mind.mp3"),
(null,"Loveland","Pop","Milky Chance","Milky Chance - Loveland.mp3"),
(null,"Stolen Dance","Pop","Milky Chance","Milky Chance - Stolen Dance.mp3"),
(null,"Atalho","Samba","Mosquito","Mosquito - Atalho.mp3"),
(null,"Hopeless Wanderer","Alternativo","Mumford and Sons","Mumford and Sons - Hopeless Wanderer.mp3"),
(null,"A Cor","Reggae","Natiruts","Natiruts - A Cor.mp3"),
(null,"Andei Só","Reggae","Natiruts","Natiruts - Andei Só.mp3"),
(null,"Au de Cabeça","Reggae","Natiruts","Natiruts - Au de Cabeça.mp3"),
(null,"Deixa o Menino Jogar","Reggae","Natiruts","Natiruts - Deixa o Menino Jogar.mp3"),
(null,"Dentro da Música II","Reggae","Natiruts","Natiruts - Dentro da Música II.mp3"),
(null,"Espero Que um Dia","Reggae","Natiruts","Natiruts - Espero Que um Dia.mp3"),
(null,"Glamour Tropical","Reggae","Natiruts","Natiruts - Glamour Tropical.mp3"),
(null,"Groove Bom","Reggae","Natiruts","Natiruts - Groove Bom.mp3"),
(null,"Já Chorei Demais","Reggae","Natiruts","Natiruts - Já Chorei Demais.mp3"),
(null,"Liberdade Pra Dentro da Cabeça","Reggae","Natiruts","Natiruts - Liberdade Pra Dentro da Cabeça.mp3"),
(null,"Meu Reggae é Roots","Reggae","Natiruts","Natiruts - Meu Reggae é Roots.mp3"),
(null,"O Carcará e a Rosa","Reggae","Natiruts","Natiruts - O Carcará e a Rosa.mp3"),
(null,"Pedras Escondidas","Reggae","Natiruts","Natiruts - Pedras Escondidas.mp3"),
(null,"Pérola Negra","Reggae","Natiruts","Natiruts - Pérola Negra.mp3"),
(null,"Quero Ser Feliz Também","Reggae","Natiruts","Natiruts - Quero Ser Feliz Também.mp3"),
(null,"Reggae de Raiz","Reggae","Natiruts","Natiruts - Reggae de Raiz.mp3"),
(null,"Reggae Power - Esperar o Sol","Reggae","Natiruts","Natiruts - Reggae Power - Esperar o Sol.mp3"),
(null,"Sorri Sou Rei","Reggae","Natiruts","Natiruts - Sorri Sou Rei.mp3"),
(null,"Supernova","Reggae","Natiruts","Natiruts - Supernova.mp3"),
(null,"Vento Sol Coração","Reggae","Natiruts","Natiruts - Vento Sol Coração.mp3"),
(null,"Você Me Encantou Demais","Reggae","Natiruts","Natiruts - Você Me Encantou Demais.mp3"),
(null,"Quando eu Contar - Deixa a Vida me Levar","Samba","Serginho Meriti","Serginho Meriti - Quando eu Contar - Deixa a Vida me Levar.mp3"),
(null,"Os Papeis - O samba e meu dom","Samba","Wilson das Neves","Wilson das Neves - Os Papeis - O samba e meu dom.mp3"),
(null,"Deus é Mais","Samba","Xande de Pilares","Xande de Pilares - Deus é Mais.mp3"),
(null,"O Penetra Pai Coruja - Vacilao","Samba","Ze Roberto","Ze Roberto - O Penetra Pai Coruja - Vacilao.mp3");


